-- 1) Create a new database for managing customer orders.
	CREATE DATABASE CustomerOrdersDB;
	USE CustomerOrdersDB;

-- 2) Create a table to store order details with columns for order ID, customer name, product name, quantity, price, and order date.
	CREATE TABLE orders (
    order_id INT PRIMARY KEY AUTO_INCREMENT,
    customer_name VARCHAR(100),
    product_name VARCHAR(100),
    quantity INT,
    price DECIMAL(10,2),
    order_date DATE
);

-- 3) Insert at least 10 sample records into the table for different customers and products.
	INSERT INTO orders (customer_name, product_name, quantity, price, order_date) VALUES
	('Amit Sharma', 'Laptop', 1, 55000, '2026-02-01'),
	('Priya Mehta', 'Mobile', 2, 20000, '2026-02-03'),
	('Rahul Verma', 'Tablet', 1, 30000, '2026-02-05'),
	('Sneha Patil', 'Headphones', 3, 3000, '2026-02-07'),
	('Amit Sharma', 'Mouse', 5, 500, '2026-02-08'),
	('Priya Mehta', 'Laptop', 1, 60000, '2026-02-10'),
	('Rahul Verma', 'Mobile', 3, 15000, '2026-02-12'),
	('Neha Singh', 'Keyboard', 4, 1500, '2026-02-15'),
	('Rohan Das', 'Monitor', 2, 12000, '2026-02-18'),
	('Sneha Patil', 'Laptop', 1, 58000, '2026-02-20');

-- 4) Display all the data from the table.
	SELECT * FROM orders;

-- 5) Show customer name, product name, and the total amount of each order calculated using quantity and price.
	SELECT customer_name, product_name, 
       quantity * price AS total_amount
	FROM orders;

-- 6) Display only those customers whose total order amount exceeds 40,000.
	SELECT customer_name, 
       SUM(quantity * price) AS total_spent -- (sum) is use to because 1 person buy many objects 
	FROM orders
	GROUP BY customer_name
	HAVING total_spent > 40000;

-- 7) Retrieve a list of all customers with a 10% discount applied on the total order amount.
	SELECT customer_name,
       SUM(quantity * price) AS total_amount,
       SUM(quantity * price) * 0.90 AS discounted_amount
	FROM orders
	GROUP BY customer_name;

-- 8) Display customer name, product name, total amount, and the total amount after adding 18% tax.
	SELECT customer_name, product_name,
       quantity * price AS total_amount,
       (quantity * price) * 1.18 AS total_with_tax
	FROM orders;

-- 9) List all products arranged in ascending order of their price.
	SELECT DISTINCT product_name, price FROM orders
	ORDER BY price ASC;

-- 10) Show all orders arranged from the highest total order amount to the lowest.
	SELECT *, quantity * price AS total_amount
	FROM orders
	ORDER BY total_amount DESC;
    
-- 11) Display all customers in alphabetical order by their names.
	SELECT DISTINCT customer_name
	FROM orders
	ORDER BY customer_name ASC;

-- 12) Display each product and the total quantity ordered for that product.
	SELECT product_name,
       SUM(quantity) AS total_quantity
	FROM orders
	GROUP BY product_name;

-- 13) Find the average price of each product type.
	SELECT product_name,
       AVG(price) AS average_price
	FROM orders
	GROUP BY product_name;

-- 14) Calculate the total revenue generated by each product.
	SELECT product_name,
       SUM(quantity * price) AS total_revenue
	FROM orders
	GROUP BY product_name;

-- 15) Display each customer and the total number of orders they have placed.
	SELECT customer_name,
       COUNT(order_id) AS total_orders
	FROM orders
	GROUP BY customer_name;

-- 16) Show the highest order amount placed by each customer.
	SELECT customer_name,
       MAX(quantity * price) AS highest_order
	FROM orders
	GROUP BY customer_name;

-- 17) Display the lowest price of the products purchased by each customer.
	SELECT customer_name,
       MIN(price) AS lowest_price
	FROM orders
	GROUP BY customer_name;

-- 18) Find the total number of unique products sold and the total quantity of all products.
	SELECT COUNT(DISTINCT product_name) AS unique_products,
       SUM(quantity) AS total_quantity
	FROM orders;

-- 19) Display the customers whose total purchase amount is greater than 100,000.
	SELECT customer_name,
       SUM(quantity * price) AS total_spent
	FROM orders
	GROUP BY customer_name
	HAVING total_spent > 100000;

-- 20) Show each customer and their total spending, arranged from highest to lowest 60000
	SELECT customer_name,
       SUM(quantity * price) AS total_spending
	FROM orders
	GROUP BY customer_name
	HAVING total_spending > 60000
	ORDER BY total_spending DESC;